### ISSUE TITLE
VaccumDevice depreciated error message

### ISSUE THREAD

**Issue by klec00** [walthowd/ha-automower#10]
Installed via HACS and configured my automower. When restarting HA,the following error message appears in the log:

2020-06-10 16:18:39 WARNING (MainThread) [homeassistant.components.vacuum] VacuumDevice is deprecated, modify AutomowerDevice to extend VacuumEntity

**Comment by andreasfelder** [comment]
Just noticed the same. Found this article that shows the code to be used as an example:
https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/
I can try take a look at this however need to figure out best way for me to test in my environment first.

**Comment by walthowd** [comment]
Just updated, thank you @andreasfelder

**Comment by klec00** [comment]
Works fine now, thanks!
