### ISSUE TITLE
 Google Maps card link no longer available 

### ISSUE THREAD

**Issue by lowrisk75** [walthowd/ha-automower#20]
The link for the google maps card is no longer available

https://www.home-assistant.io/cookbook/google_maps_card/

if anyway would have a tutorial or something that would be great.

**Comment by walthowd** [comment]
You can pull it up here:

https://web.archive.org/web/20201127065354/https://www.home-assistant.io/cookbook/google_maps_card/

I use the camera entity to do a mobile push alert whenever the mower has an issue. You can tell at a glance where the mower is if you have a large yard.

If you just want something for the front end, the lovelace map card is great:

```
dark_mode: true
default_zoom: 19
entities:
  - entity: device_tracker.automower
hours_to_show: 2
title: Automower Location History
type: map
```

**Comment by lowrisk75** [comment]
Thank you, the Lovelace map card is just perfect, thanks a lot
