### ISSUE TITLE
Home Assistant 2021.9.6

### ISSUE THREAD

**Issue by nolenjohan** [walthowd/ha-automower#22]
When updating from Home Assistant 2021.9.5 to Home Assistant 2021.9.6 I get the below message, same issue on two (2) separate instances of HA, tried to reinstall Automower and restarted HA, same issue.

![screenshot 1322](https://user-images.githubusercontent.com/34334118/133046604-65fce12b-bd22-4fb0-b09d-a9163638ac2f.jpg)

**Comment by StephanFastxl** [comment]
i have the same issue:

Log gives:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 255, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/automower/__init__.py", line 223, in setup
    hass.data[DOMAIN]['devices'].append(AutomowerDevice(robot, api))
  File "/config/custom_components/automower/__init__.py", line 239, in __init__
    self._model = meta['model']
KeyError: 'model'`

**Comment by cokeman0** [comment]
same here.. started today

**Comment by theailer** [comment]
Yeah me tio

**Comment by donoghdb** [comment]
Me too ☺️

**Comment by RicoRehn** [comment]
Same here after update.
I fixed it temporarily buy changing row 239 "self._model = meta['model']" to "self._model = None" in init.py

**Comment by dowermyr** [comment]
> Same here after update.
> I fixed it temporarily by changing row 239 "self._model = meta['model']" to "self._model = None" in init.py

What happens when you change this? Any drawbacks?

**Comment by Ralf1977** [comment]
Same issue here

**Comment by MRobi1** [comment]
I don't know if this is related to 2021.9.6. 
I just updated the host OS to 6.4 this morning and have the same error. My core is still 2021.9.4

**Comment by RicoRehn** [comment]
> I don't know if this is related to 2021.9.6.
> I just updated the host OS to 6.4 this morning and have the same error. My core is still 2021.9.4

Strange, i have host still in 6.3 and core 2021.9.6

**Comment by RicoRehn** [comment]
> > Same here after update.
> > I fixed it temporarily by changing row 239 "self._model = meta['model']" to "self._model = None" in init.py
> 
> What happens when you change this? Any drawbacks?

I have not gotten any error yet, but i can't say for sure. My automations still works, which utilize start/stop, return home.

**Comment by walthowd** [comment]
https://github.com/walthowd/ha-automower/pull/23
