### ISSUE TITLE
Integration can not be loaded

### ISSUE THREAD

**Issue by dowermyr** [walthowd/ha-automower#26]
HA 2022.3.7
Integation no longer works.
From the log:
Felet härrör från en anpassad integration.

Logger: homeassistant.setup
Source: custom_components/automower/__init__.py:217
Integration: automower (documentation)
First occurred: 10:10:40 (1 occurrences)
Last logged: 10:10:40

Error during setup of component automower
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/automower/__init__.py", line 217, in setup
    robots = api.list_robots()
  File "/usr/local/lib/python3.9/site-packages/pyhusmow/husmow.py", line 162, in list_robots
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers

**Comment by nolenjohan** [comment]
I have the same issue, running Home Assistant 2022.3.7

**Comment by DanoneKiD** [comment]
Hi, same issue here. The url on the pyhusmow library is no more reachable.

**Comment by splunkenizer** [comment]
Jep, the same over here as well. Happened with the upgrade of the HACS version.

**Comment by esukka** [comment]
Same here:

Tämä virhe on peräisin mukautetusta integroinnista.

Logger: homeassistant.setup
Source: custom_components/automower/__init__.py:217
Integration: automower (documentation)
First occurred: 17.09.00 (1 occurrences)
Last logged: 17.09.00

Error during setup of component automower
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/automower/__init__.py", line 217, in setup
    robots = api.list_robots()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyhusmow/husmow.py", line 162, in list_robots
    response.raise_for_status()
  File "/srv/homeassistant/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers

**Comment by walthowd** [comment]
It appears the Husqvarna API is either down, or this version has been discontinued. 😱

**Comment by splunkenizer** [comment]
> You can migrate to this component https://github.com/Thomas55555/husqvarna_automower

What I do not understand from the docs is, if this one has status sensors as well, like the status of the the automower and GPS position to show on a map. Like this one can do.

**Comment by walthowd** [comment]
Yes, the official API does not give you GPS coordinates, which I found very useful. I will not have time to really chase this but if anyone can look:

```
docker run --rm -it python:3.10 /bin/bash
pip3 install pyhusmow
husmow --login <youremail> --password <yourpassword>
```

If we can get login working, and the rest of the "old" API is still functional we can fork `pyhusmow` on pypi and keep going. :)

**Comment by Alfiegerner** [comment]
No dice with pyhusmow:

```
root@f66541666602:/# husmow --login login@gmail.com --password
Logger configured
Logged in successfully
Updated token
[ERROR] 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers. Retrying to send the command 1
[ERROR] 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers. Retrying to send the command 2
[ERROR] Failed to send the command
Done
```

**Comment by Alfiegerner** [comment]
But [Automowy](https://github.com/tmonjalo/automowy)  still looks to be working: in as far as it's logging in and retrieving settings for me. Here are the URLs it's using:
```
AUTH_URL_BASE = 'https://iam-api.dss.husqvarnagroup.net/api/v3/token/'
    URL_BASE = 'https://amc-api.dss.husqvarnagroup.net/app/v1/'
```
I use automowy together with this project to change settings, i.e. change guide wire configuration to make mower focus on different area at night.

**Comment by xerxel** [comment]
I can't tell if this is the same error or not. All I know is that I updated HACS and then HA today and suddenly it stopped working! Is the fix to roll back to a previous version of HACS? I don't remember updating the ha-automower component.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/automower/__init__.py", line 217, in setup
    robots = api.list_robots()
  File "/usr/local/lib/python3.9/site-packages/pyhusmow/husmow.py", line 162, in list_robots
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers`

**Comment by Alfiegerner** [comment]
Yeah that's the same issue. They've taken away that end point by the look of it, though the app/v1 still looks up.

**Comment by chinezbrun** [comment]
same here. not working with 2022.04.0

**Comment by GitHobi** [comment]
> > You can migrate to this component https://github.com/Thomas55555/husqvarna_automower
> 
> What I do not understand from the docs is, if this one has status sensors as well, like the status of the the automower and GPS position to show on a map. Like this one can do.

This integration provides pretty much the same data as this one here.
The only big difference I've seen so far: Walthowds integration provides sensors for "next start" - while thomas55555 even provides a calendar with all start / stop dates for the next week. Additionally thomas55555 provides the possibility to get / set the cutting height and get / set the status of the lights.  Biggest benefit: The integration seems to use the official API - so it still works (disadvantage: You need to register for an API key - takes 2 minutes).

**Comment by Alfiegerner** [comment]
My experience is that the official API isn't working as well - GPS updates are slower, battery amounts incorrect, status updates slow or incorrect.  This may just be a sample of 1 outlier but I would move back to the pyhusmow version if it were available.

**Comment by JoeAstor** [comment]
Any news when the integration would be back online? Official api doesn´t work as good as this integration...

**Comment by MRobi1** [comment]
Just a few days using the official API and I agree that it doesn't work nearly as good as this one did. Feels like battery only updates at 33, 67 and 100%, and as others have said GPS updates and status updates are significantly slower.

**Comment by nicole-ashley** [comment]
My battery updates while charging are just as regular with the official API as before, however the updates while in use are now only as frequent as while charging (every 5-10%). They used to be every minute. GPS updates are very infrequent now compared to every minute on the old API.

Note however that these changes are even true for the official app before and after this integration went down. So it's possible that these are backend changes that would still be an issue even if connectivity to the old API was restored.

**Comment by JoeAstor** [comment]
Any news?

**Comment by Alfiegerner** [comment]
@JoeAstor There is a pull request for a fix that needs testing before it can be merged. I won't be able to get to it for a while so if someone else could test and add it brief notes on the pull request than @walthowd can make it available.

**Comment by Alfiegerner** [comment]
PR https://github.com/walthowd/ha-automower/pull/27

To test, copy changes files from PR into custom_components/automower (or replace dir completely with PR fork) and restart HA.
